// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASY1IuO29fwVoRYuKqts73t3rcLW3WkIs',
    appId: '1:925837090965:web:4c7e46a25623ab3fd83b9c',
    messagingSenderId: '925837090965',
    projectId: 'baitimart',
    authDomain: 'baitimart.firebaseapp.com',
    storageBucket: 'baitimart.firebasestorage.app',
    measurementId: 'G-6BBCVEWRYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoAlMJiwoib4AFsYLw-A3akMpAUCkcuBw',
    appId: '1:925837090965:android:0f360b100a145aaed83b9c',
    messagingSenderId: '925837090965',
    projectId: 'baitimart',
    storageBucket: 'baitimart.firebasestorage.app',
  );
}
